service: serverless

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  profile: serverless

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:
    MyDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'serverless'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
